# Image de base Node.js
FROM node:latest

# Définition du répertoire de travail
WORKDIR /defi

# Copie du code source de l'application
COPY defi.js .

# Exposition du port 3000 pour accéder à l'application
EXPOSE 3000

# Commande de démarrage de l'application
CMD [ "node", "defi.js" ]
